#!/bin/bash

if [ $# -lt 1 ]; then
        echo Usage: get_ge_assaylist \<filename\>
        exit 1
fi

filename=$1

cut -f2 /csprod/flatfiles/ABWESTCOAST/$filename | tail -n +2 | sed -e "s/^\|$/'/g" | tr '\n' ',' | sed -e 's/,$/\n/g' -e 's/,/,\n/g'
