#!/bin/bash

if [ $# -lt 1 ]; then
        echo Usage: srchsas keyword
        exit 1
fi

grep -ir --color=always $1 ~/maharjas/thermo_*.txt | sort | uniq | sed '/_bc.txt/d'
#cut -f11,2,4 -d',' ~/KPLOC.csv | awk -F',' '{print $3, $1, $2}' | grep -is --color=always $1
cut -f1,5 -d':'    /etc/passwd | grep -is --color=always $1
